apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voms-maint
  name: voms-maint-pod
  namespace: voms
spec:
  replicas: 0
  selector:
    matchLabels:
      app: voms-maint
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: voms-maint
      name: voms-maint
    spec:
      hostname: 'voms'
      nodeSelector:
        constance-lustre: v1
      containers:
      - name: voms-maint
        image: pnnlhep/voms-server-front:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voms-secrets
              key: mysql-root-password
        volumeMounts:
         - name: dump-volume
           mountPath: /pic
         - name: startscript
           mountPath: "/etc/start.sh"
           subPath: start.sh
         - name: voms-certs
           mountPath: "/etc/grid-security/hostcert.pem"
           subPath: hostcert.pem
           readOnly: true
         - name: voms-certs
           mountPath: "/etc/grid-security/hostkey.pem"
           subPath: hostkey.pem
           readOnly: true
        command: ["/etc/do-nothing.sh"]
      volumes:
        - name: dump-volume
          hostPath:
            path: /pic-dtemp
            type: Directory
        - name: voms-certs
          secret:
            secretName: voms-secrets
            items:
              - key: voms-hostcert
                path: hostcert.pem
                mode: 420
              - key: voms-hostkey
                path: hostkey.pem
                mode: 256
        - name: mysql-root-passsword
          secret:
            secretName: voms-secrets
        - name: startscript
          configMap:
            name: voms-frontend
            items:
              - key: startscript
                path: start.sh
                mode: 493
