apiVersion: v1
kind: ConfigMap
metadata:
  name: voms-frontend
  namespace: voms
data:
  startscript: |
    #!/bin/bash

    # This seems like it shouldn't be necessary but can't find a better way
    sed -i 's/host=.*/host=voms.hep.pnnl.gov/' /etc/voms-admin/voms-admin-server.properties

    echo  >> /etc/voms-admin/voms-admin-server.properties
    echo "#" >> /etc/voms-admin/voms-admin-server.properties
    echo "tls_exclude_cipher_suites=TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_RSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_DSS_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256" >> /etc/voms-admin/voms-admin-server.properties
    echo "tls_exclude_protocols=TLSv1,TLSv1.1" >> /etc/voms-admin/voms-admin-server.properties

    # This horrible hack fixes up quoting in the voms-db-util script so that
    # it won't gag on the apostrophe in the issuer name ("Let's Encrypt") in
    # our vomscert.pem file.  For sure only do this once!:
    if [[ ! -e /tmp/fixquotes.sed ]]
    then
      echo "/java -cp/y/'\"/\"'/" > /tmp/fixquotes.sed
      sed -f /tmp/fixquotes.sed -i /usr/sbin/voms-db-util
    fi

    voms-configure install \
    --vo=project8 \
    --hostname=voms.hep.pnnl.gov \
    --skip-database \
    --dbtype=mysql \
    --dbname=voms_project8 \
    --dbusername=root \
    --dbpassword=$MYSQL_ROOT_PASSWORD \
    --dbhost=$VOMS_BACKEND_SERVICE_HOST \
    --dbport=3306 \
    --dbauser=root \
    --dbapwd=$MYSQL_ROOT_PASSWORD \
    --core-port=15030 \
    --smtp-host=emailgw02.pnnl.gov \
    --mail-from='david.cowley@pnnl.gov'

    voms-configure install \
    --vo=ccsdi \
    --hostname=voms.hep.pnnl.gov \
    --skip-database \
    --dbtype=mysql \
    --dbname=voms_ccsdi \
    --dbusername=root \
    --dbpassword=$MYSQL_ROOT_PASSWORD \
    --dbhost=$VOMS_BACKEND_SERVICE_HOST \
    --dbport=3306 \
    --dbauser=root \
    --dbapwd=$MYSQL_ROOT_PASSWORD \
    --core-port=15020 \
    --smtp-host=emailgw02.pnnl.gov \
    --mail-from='david.cowley@pnnl.gov'

    #/sbin/service postfix start
    /sbin/service voms-admin start
    /sbin/service voms start

    while (true)
    do
        sleep 1800
        # Bad idea.  This falls down and can't get up when I do it.  the
        # service doesn't come back, so no ports (15020, 15030) for clients
        # to connect to.
        # /sbin/service voms reload
    done
