apiVersion: v1
kind: PersistentVolume
metadata:
  name: voms-project8-backfs
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - p1.hep.pnnl.gov
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/data/mysql-voms-project8
    type: ""
  persistentVolumeReclaimPolicy: Retain
