apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voms-project8-db
  namespace: voms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: voms-project8-backfs
